name: Keep Render App Alive

on:
  schedule:
    # Runs every 10 minutes
    - cron: '*/4 * * * *'
  workflow_dispatch: # Allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP request
        run: |
          curl -s -o /dev/null -w "%{http_code}" https://innfinity.onrender.com/
      - name: Check time
        run: date 